# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 327f7add2718674838135102adeeea3c89cc357f85c12e94745254412a191ca01ec6d9f7de3c29df56c25a9c4e7c366318a633066cc84a947a3452575f499696

test:
  secret_key_base: 5ce4db40aac8d57621219fb8884c40c8eccf80b5ee6c9d9588bdf48323b2d5f7754cce5c9919243800a8655b392e50c555e007bdfde9a82a8734a514556b80ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
